import { test, expect, beforeEach, afterEach } from "bun:test";
import { join } from "path";
import { readFile, mkdir } from "fs/promises";
import { createTestEnv, type TestEnv, type MockSkillRepo } from "../helpers/test-env.js";
import { install } from "../../src/commands/install.js";
import { upgradePackage } from "../../src/commands/upgrade.js";

let env: TestEnv;
let consumerDir: string;

beforeEach(async () => {
  env = await createTestEnv();
  // Create a consumer directory simulating a repo that uses rules
  consumerDir = join(env.root, "consumer-repo");
  await mkdir(join(consumerDir, "docs", "agents-md"), { recursive: true });
});

afterEach(async () => {
  await env.cleanup();
});

/**
 * Create a mock rules package repo with templates.
 *
 * `opts.type` defaults to "rules" but can be overridden to model a package
 * that ships templates alongside other artefacts (e.g. "governance-overlay"
 * — the compass case from a-181). The upgrade pipeline should regenerate
 * templates for any package declaring provides.templates[], regardless of type.
 */
async function createMockRulesRepo(
  root: string,
  opts?: { version?: string; type?: string },
): Promise<MockSkillRepo> {
  const repoDir = join(root, "mock-rules-pkg");

  // Create templates
  await Bun.write(
    join(repoDir, "templates", "CLAUDE.md.template"),
    `<!-- Generated by arc. Do not edit directly. -->

# {REPO_NAME} -- {REPO_DESCRIPTION}

{REPO_DESCRIPTION}

<!-- inject:after:description -->

## Critical Rules

- Standard rule 1
- Standard rule 2

<!-- inject:after:critical-rules -->

## Labels

| Label | Purpose |
|-------|---------|
| bug | Bugs |

{PROJECT_SPECIFIC_LABELS}

## Footer
`,
  );

  // Create arc-manifest.yaml
  await Bun.write(
    join(repoDir, "arc-manifest.yaml"),
    `schema: arc/v1
name: compass-standards
version: ${opts?.version ?? "0.3.0"}
type: ${opts?.type ?? "rules"}
tier: official
author:
  name: metafactory
  github: the-metafactory
provides:
  templates:
    - source: templates/CLAUDE.md.template
      target: CLAUDE.md
      config: agents-md.yaml
`,
  );

  // Initialize git repo
  Bun.spawnSync(["git", "init"], { cwd: repoDir, stdout: "pipe", stderr: "pipe" });
  Bun.spawnSync(["git", "add", "."], { cwd: repoDir, stdout: "pipe", stderr: "pipe" });
  Bun.spawnSync(
    ["git", "-c", "user.name=Test", "-c", "user.email=test@test.com", "commit", "-m", "Initial commit"],
    { cwd: repoDir, stdout: "pipe", stderr: "pipe" },
  );

  return { path: repoDir, url: repoDir };
}

test("install rules package generates CLAUDE.md in consumer dir", async () => {
  const rulesRepo = await createMockRulesRepo(env.root);

  // Set up consumer config
  await Bun.write(
    join(consumerDir, "agents-md.yaml"),
    `template: compass-standards
repo_name: test-project
repo_description: "A test project"
`,
  );

  const result = await install({
    arc: env.arc, host: env.host,
    db: env.db,
    repoUrl: rulesRepo.url,
    yes: true,
    consumerDir,
  });

  expect(result.success).toBe(true);
  expect(result.name).toBe("compass-standards");

  // Verify generated CLAUDE.md
  const output = await readFile(join(consumerDir, "CLAUDE.md"), "utf-8");
  expect(output).toContain("# test-project -- A test project");
  expect(output).toContain("A test project");
  expect(output).toContain("- Standard rule 1");
});

test("install rules package with sections injects content", async () => {
  const rulesRepo = await createMockRulesRepo(env.root);

  // Consumer config with sections
  await Bun.write(
    join(consumerDir, "agents-md.yaml"),
    `template: compass-standards
repo_name: grove
repo_description: "PAI Event Relay"
sections:
  - position: "after:description"
    file: docs/agents-md/architecture.md
  - position: "after:critical-rules"
    file: docs/agents-md/critical-rules.md
extra_labels:
  - name: visibility
  - name: network
`,
  );

  // Section files
  await Bun.write(
    join(consumerDir, "docs", "agents-md", "architecture.md"),
    "## Architecture\n\nGrove is a Discord bot.",
  );
  await Bun.write(
    join(consumerDir, "docs", "agents-md", "critical-rules.md"),
    "- Never use empty catch blocks",
  );

  const result = await install({
    arc: env.arc, host: env.host,
    db: env.db,
    repoUrl: rulesRepo.url,
    yes: true,
    consumerDir,
  });

  expect(result.success).toBe(true);

  const output = await readFile(join(consumerDir, "CLAUDE.md"), "utf-8");
  expect(output).toContain("# grove -- PAI Event Relay");
  expect(output).toContain("## Architecture\n\nGrove is a Discord bot.");
  expect(output).toContain("- Never use empty catch blocks");
  expect(output).toContain("| `visibility` |");
  expect(output).toContain("| `network` |");
  // Injection markers should be cleaned up
  expect(output).not.toContain("<!-- inject:");
});

test("upgrade --force regenerates templates for a non-rules package that provides templates", async () => {
  // a-181: a package can declare provides.templates[] while having a primary
  // type other than "rules" (compass ships templates but resolves to a
  // non-rules artifact type). Both the install pass and the upgrade pipeline
  // must regenerate the consumer's CLAUDE.md regardless of primary type.
  const overlayRepo = await createMockRulesRepo(env.root, { type: "component" });

  await Bun.write(
    join(consumerDir, "agents-md.yaml"),
    `template: compass-standards
repo_name: halden
repo_description: "Overlay consumer"
sections:
  - position: "after:description"
    file: docs/agents-md/architecture.md
`,
  );
  await Bun.write(
    join(consumerDir, "docs", "agents-md", "architecture.md"),
    "## Architecture\n\nFirst version.",
  );

  await install({
    arc: env.arc, host: env.host,
    db: env.db,
    repoUrl: overlayRepo.url,
    yes: true,
    consumerDir,
  });

  // Install-time generation picked up v1.
  let output = await readFile(join(consumerDir, "CLAUDE.md"), "utf-8");
  expect(output).toContain("First version.");

  // Section content drifts with no package version bump — the exact case
  // `arc upgrade compass --force` must handle.
  await Bun.write(
    join(consumerDir, "docs", "agents-md", "architecture.md"),
    "## Architecture\n\nSecond version.",
  );

  // findConsumerRepos scans BLUEPRINT_DEV_ROOT — point it at the test root
  // so the consumer dir is discovered.
  const priorDevRoot = process.env.BLUEPRINT_DEV_ROOT;
  process.env.BLUEPRINT_DEV_ROOT = env.root;
  try {
    const result = await upgradePackage(env.db, env.arc, env.host, "compass-standards", { force: true });
    expect(result.success).toBe(true);
  } finally {
    if (priorDevRoot === undefined) delete process.env.BLUEPRINT_DEV_ROOT;
    else process.env.BLUEPRINT_DEV_ROOT = priorDevRoot;
  }

  // Pre-fix: the upgrade gate required type === "rules", so this was a
  // no-op and CLAUDE.md still said "First version." Post-fix: regenerated.
  output = await readFile(join(consumerDir, "CLAUDE.md"), "utf-8");
  expect(output).toContain("Second version.");
  expect(output).not.toContain("First version.");
});

test("rules package recorded as rules artifact type in DB", async () => {
  const rulesRepo = await createMockRulesRepo(env.root);

  await Bun.write(
    join(consumerDir, "agents-md.yaml"),
    `template: compass-standards
repo_name: test
repo_description: "Test"
`,
  );

  await install({
    arc: env.arc, host: env.host,
    db: env.db,
    repoUrl: rulesRepo.url,
    yes: true,
    consumerDir,
  });

  const row = env.db.prepare("SELECT artifact_type FROM skills WHERE name = ?").get("compass-standards") as { artifact_type: string };
  expect(row.artifact_type).toBe("rules");
});
